SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[logger4]'
GO
ALTER TABLE [dbo].[logger4] DROP CONSTRAINT [Logger4PK]
GO
PRINT N'Dropping constraints from [dbo].[logger4]'
GO
ALTER TABLE [dbo].[logger4] DROP CONSTRAINT [DF__logger4__LogDate__09A971A2]
GO
PRINT N'Dropping [dbo].[logger4]'
GO
DROP TABLE [dbo].[logger4]
GO

﻿SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

