SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[UpdateCustomer]'
GO
ALTER PROCEDURE [dbo].[UpdateCustomer]
  @CustomerID INT
AS
BEGIN
  DECLARE @c VARCHAR(50)
  SELECT @c = PeopleName FROM dbo.GetNewName AS gnn
  UPDATE dbo.Customer
   SET CustomerName = @c
   WHERE CustomerID = @CustomerID

END
GO

SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

