SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[SizeTest]'
GO
ALTER TABLE [dbo].[SizeTest] DROP CONSTRAINT [SizeTestPK]
GO
PRINT N'Altering [dbo].[SizeTest]'
GO
ALTER TABLE [dbo].[SizeTest] ALTER COLUMN [myid] [char] (2) NOT NULL
GO
PRINT N'Creating primary key [SizeTestPK] on [dbo].[SizeTest]'
GO
ALTER TABLE [dbo].[SizeTest] ADD CONSTRAINT [SizeTestPK] PRIMARY KEY CLUSTERED ([myid])
GO

﻿SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

