SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[logger2]'
GO
ALTER TABLE [dbo].[logger2] DROP CONSTRAINT [Logger2PK]
GO
PRINT N'Dropping constraints from [dbo].[logger2]'
GO
ALTER TABLE [dbo].[logger2] DROP CONSTRAINT [DF__logger2__LogDate__06CD04F7]
GO
PRINT N'Dropping [dbo].[logger2]'
GO
DROP TABLE [dbo].[logger2]
GO

﻿SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

