SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[CurrentFreightRates]'
GO
DROP VIEW [dbo].[CurrentFreightRates]
GO
PRINT N'Altering [dbo].[FreightRate]'
GO
ALTER TABLE [dbo].[FreightRate] DROP
COLUMN [validUntil]
GO
EXEC sp_rename N'[dbo].[FreightRate].[statustext]', N'status', N'COLUMN'
GO

SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

