SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[logger]'
GO
ALTER TABLE [dbo].[logger] DROP CONSTRAINT [LoggerPK]
GO
PRINT N'Dropping constraints from [dbo].[logger]'
GO
ALTER TABLE [dbo].[logger] DROP CONSTRAINT [DF__logger__LogDate__02FC7413]
GO
PRINT N'Dropping [dbo].[logger]'
GO
DROP TABLE [dbo].[logger]
GO

﻿SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

