SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[logger]'
GO
CREATE TABLE [dbo].[logger]
(
[LogID] [int] NOT NULL IDENTITY(1, 1),
[LogDate] [datetime] NULL CONSTRAINT [DF__logger__LogDate__02FC7413] DEFAULT (getdate()),
[LogMsg] [varchar] (500) NULL
)
GO
PRINT N'Creating primary key [LoggerPK] on [dbo].[logger]'
GO
ALTER TABLE [dbo].[logger] ADD CONSTRAINT [LoggerPK] PRIMARY KEY CLUSTERED ([LogID])
GO

﻿SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

