SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[OrderReturn]'
GO
ALTER TABLE [dbo].[OrderReturn] ALTER COLUMN [Reason] [varchar] (1000) NULL
GO

