SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[Shipper]'
GO
CREATE TABLE [dbo].[Shipper]
(
[shipperid] [int] NULL,
[Shippername] [varchar] (20) NULL
)
GO

